name: CI/CD Pipeline for MCP Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image
      - name: Build Docker image
        run: docker build -t mcpserver:latest .

      # Run the container for testing
      - name: Test Docker container
        run: |
          docker run -d -p 8080:8080 --name mcpserver mcpserver:latest
          sleep 5 # Wait for server to start
          # Test initialize method
          echo '{"jsonrpc":"2.0","method":"initialize","params":{},"id":1}' | nc localhost 8080
          # Test tools/list
          echo '{"jsonrpc":"2.0","method":"tools/list","id":2}' | nc localhost 8080
          docker stop mcpserver

      # Push to Docker Hub on push to main
      - name: Push Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker tag mcpserver:latest ${{ secrets.DOCKER_USERNAME }}/mcpserver:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/mcpserver:latest