name: CI/CD Pipeline for MCP Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build and test Docker image
      - name: Build and test Docker image
        run: |
          docker build -t mcpserver:latest .
          docker run -d -p 8080:8080 --name mcpserver -e XAI_API_KEY=${{ secrets.XAI_API_KEY }} mcpserver:latest
          sleep 5
          echo '{"jsonrpc":"2.0","method":"initialize","params":{},"id":1}' | nc -w 2 localhost 8080
          echo '{"jsonrpc":"2.0","method":"tools/list","id":2}' | nc -w 2 localhost 8080
          docker stop mcpserver